version: '3.8'

x-logging: 
  &default-logging
  driver: 'json-file'
  options:
    max-size: '1M'
    max-file: '5'

services:
  db:
    image: 'qdrant/qdrant:latest'
    restart: always
    volumes:
      - qdrant_storage:/qdrant_data
    ports:
      - '6333:6333'
      - '6334:6334'
    environment:
      - QDRANT__SERVICE__GRPC_PORT=6334
    networks:
      - qdrant-network
    logging: *default-logging

  fastapi:
    build: backend
    restart: always
    depends_on:
      - db
    ports:
      - 127.0.0.1:8000:8000
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    logging: *default-logging
    networks:
    - qdrant-network
    command: fastapi dev --host 0.0.0.0 --port 8000

volumes:
  qdrant_storage:

networks:
  qdrant-network:
    driver: bridge