x-logging: 
  &default-logging
  driver: 'json-file'
  options:
    max-size: '1M'
    max-file: '5'

services:
  db:
    image: 'qdrant/qdrant:latest'
    restart: always
    volumes:
      - qdrant_storage:/qdrant_data
    ports:
      - '6333:6333'
      - '6334:6334'
    environment:
      - QDRANT__SERVICE__GRPC_PORT=6334
    networks:
      - app-network
    logging: *default-logging

  backend:
    build: .
    restart: always
    volumes:
      - ./:/app
    depends_on:
      - db
    ports:
      - 127.0.0.1:8000:8000
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    logging: *default-logging
    networks:
    - app-network
    command: uv run uvicorn backend.main:app --host 0.0.0.0 --port 8000


  frontend:
    build: .
    restart: always
    volumes:
      - .:/app
    ports:
      - "8501:8501"
    environment:
      - BACKEND_URL=http://backend:8000
    depends_on:
      - backend
    logging: *default-logging
    networks:
      - app-network
    command: uv run streamlit run backend/streamlit_app.py --server.port 8501 --server.address 0.0.0.0

volumes:
  qdrant_storage:

networks:
  app-network:
    driver: bridge